image: Ubuntu2004

environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: pypy3

build: off

install:
  - pip3 install tox

test_script:
  - tox
