name: Run checks

on: [push, pull_request]

jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        environment: ["py36", "py37", "py38", "py39", "flake8", "pypy3"]
        include:
          - environment: py36
            python: 3.6
          - environment: py37
            python: 3.7
          - environment: py38
            python: 3.8
          - environment: py39
            python: 3.9
          - environment: flake8
            python: 3.7
          - environment: pypy3
            python: pypy3

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tox
        run: |
          tox -e ${{ matrix.environment }}
